### ISSUE TITLE
Can this action be used to save the transform to a new file or overwrite an existing file?

### ISSUE THREAD

**Issue by thardy** [qetza/replacetokens-action#19]
Is the only option to save to the same file that was loaded as a source?

I have a config.json file in my NodeJs project that has default configurations that all work for local development. I have a config.template.json file that has all the tokens in it. When I build via GitHub Actions, I want to load up the config.template.json file, transform it with your action to replace those tokens with the env vars and secrets from my repo, then save the resulting file over config.json (not back into config.template.json).

I enjoy the mechanism of having a config.json that is pre-populated with working, default values, that doesn't require any work/build/action/deployment to get it working right after cloning the repo. I'd also like to be able to overwrite that file with env vars and secrets via a GitHub Action. The above is a straightforward way to do it, assuming I can save a transformed token file to a different filename than the source.

**Comment by qetza** [comment]
Hi @thardy,
Yes you can specify an output file instead of the default process which is to overwrite the source file.

To do since you use the `=>` pattern in the sources input:
```yaml
- uses: qetza/replacetokens-action@v1
  with:
    sources: config.template.json => config.json
    variables: '[${{ toJSON(vars) }},${{ toJSON(secrets) }}]' # use variables & secrets
```

This will look for the `config.template.json` in the directory `${{ github.workspace }}`, replace the tokens and write the result in `config.json` in the same directory.

You can change the directory using the `root` input or setting the relative path in the `sources` input.

If you want the output file in another directory specify the relative path from the source file after the `=>`:
```yaml
- uses: qetza/replacetokens-action@v1
  with:
    sources: config.template.json => config/config.json
    variables: '[${{ toJSON(vars) }},${{ toJSON(secrets) }}]' # use variables & secrets
```
