### ISSUE TITLE
secrets logged in workflow logs if ${{ toJSON(secrets) }} is used

### ISSUE THREAD

**Issue by danstis** [qetza/replacetokens-action#20]
When I use this step with the example:
```
- name: Replace tokens
  uses: qetza/replacetokens-action@v1
  id: replacetokens
  with:
    sources: ~/somefile.yml
    variables: '[${{ toJSON(vars) }},${{ toJSON(secrets) }}]'
    if-no-files-found: 'error'
    recursive: 'true'
```
The logs of the action include all of the secrets in an unredacted form in my GitHub Environment:
![image](https://github.com/user-attachments/assets/7c19d60e-33dd-4935-bce7-0b4210d80c97)

There should be a way to pass in secrets without being logged into the output of the workflow.
